name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  composer:
    name: composer install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup PHP cache
        uses: shivammathur/cache-extensions@1.9.0
        id: php-ext-cache
        with:
          php-version: '8.1'
          extensions: zip
          key: php81-cache
      - name: Cache PHP extensions
        uses: actions/cache@v3.2.4
        with:
          path: ${{ steps.php-ext-cache.outputs.dir }}
          key: ${{ steps.php-ext-cache.outputs.key }}
          restore-keys: ${{ steps.php-ext-cache.outputs.key }}
      - name: Setup PHP
        uses: shivammathur/setup-php@2.23.0
        with:
          php-version: '8.1'
          extensions: zip
      - name: Cache Composer dependencies
        uses: actions/cache@v3.2.4
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-scripts --no-autoloader

      - name: Generate Composer autoloader
        run: composer dump-autoload

  phpcs:
    name: phpcs
    needs: composer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup PHP cache
        uses: shivammathur/cache-extensions@1.9.0
        id: php-ext-cache
        with:
          php-version: '8.1'
          extensions: zip
          key: php81-cache
      - name: Cache PHP extensions
        uses: actions/cache@v3.2.4
        with:
          path: ${{ steps.php-ext-cache.outputs.dir }}
          key: ${{ steps.php-ext-cache.outputs.key }}
          restore-keys: ${{ steps.php-ext-cache.outputs.key }}
      - name: Setup PHP
        uses: shivammathur/setup-php@2.23.0
        with:
          php-version: '8.1'
          extensions: zip
      - name: Cache Composer dependencies
        uses: actions/cache@v3.2.4
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate code style
        run: composer phpcs:ci
